<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>

    <FrameworkReference Include="Microsoft.AspNetCore.App" />

    <!-- Database -->
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="7.0.0" />

    <!-- Configuration -->
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="7.0.0" />
    <PackageReference Include="System.Net.Http.Json" Version="7.0.0" />

    <!-- Dependency Injection -->
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0" />

    <!-- HttpClient -->
    <PackageReference Include="Microsoft.Extensions.Http" Version="7.0.0" />

    <!-- Options -->
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="7.0.0" />

    <!-- Logger -->
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="7.0.0" />

  </ItemGroup>

</Project>